services:
    postgres:
        image: postgres:latest
        container_name: postgres-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ptcgp
        ports:
            - '5433:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
